services:
  app:
    build: .
    container_name: nexOrder_app
    environment:
      - DB_URL=${DB_URL:?DB_URL is not set - see .env.example}
      - DB_USER=${DB_USER:?DB_USER is not set - see .env.example}
      - DB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is not set - see .env.example}
    ports:
      - "8080:8080"
    restart: always