# ===============================
# CONFIGURAÇÕES GERAIS DA APLICAÇÃO
# ===============================

# Nome da aplicação
spring.application.name=backend

# Define o profile ativo (test, dev, prod, etc)
spring.profiles.active=test

# Evita manter sessão JPA aberta até o fim da requisição (boa prática com DTOs)
spring.jpa.open-in-view=false


# ===============================
# CONFIGURAÇÕES DO BANCO H2 (MEMÓRIA)
# ===============================

# URL do banco H2 em memória
spring.datasource.url=jdbc:h2:mem:nexorderdb

# Usuário padrão do H2
spring.datasource.username=sa

# Senha (vazia por padrão)
spring.datasource.password=

# Habilita o console web do H2
spring.h2.console.enabled=true

# Define o caminho de acesso ao console H2
spring.h2.console.path=/h2-console


# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================

# Exibe SQL no console (útil em dev/test)
spring.jpa.show-sql=false

# Formata o SQL exibido no console
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# CONFIGURAÇÕES DO SWAGGER / OPENAPI
# ===============================

# Endpoint da documentação JSON (OpenAPI)
springdoc.api-docs.path=/api-docs

# URL da interface do Swagger UI
springdoc.swagger-ui.path=/swagger